### ISSUE TITLE
APPENDIX : Statements - TO & STEP (suggestion to remove individual heading and merge with *FOR*...TO...

### ISSUE THREAD

**Issue by memark2021** [X16Community/x16-user-guide#16]
The current pending **TO** section heading as a statement/command would be best removed and placed with **FOR**, by expanding FOR to the historic **FOR...TO...** heading.

Reason being **TO** is not an isolated statement, and must be tied to FOR   _(unless something has changed in X16?)._
STEP does not need to be presented as part of the FOR heading, as it is an optional feature and will be covered in the description.

If this is agreed, I can update the basic_command.tex file.

**Comment by memark2021** [comment]
Adding to this is the removal of **STEP** as an isolated statement currently pending info.  As mentioned, it will be explained in the FOR...TO... description and is tied to **FOR**.

NEXT is a separate command, so should keep it's section although tied to FOR.

**Comment by tomxp411** [comment]
TO can also be used with GO. GOTO is a single token, but GO TO is also valid BASIC syntax. A brief section explaining that would not be out of order.

**Comment by memark2021** [comment]
GO TO?... okay learnt something (never noticed that before).  It should still apply that **TO** is not a separate leading command/statement.  There is no "TO" something?    

When re-proofing GOTO, we can add in another bit to highlight the use of GO TO.... although, when just testing GO TO this doesn't apply to "ON X GO TO" (produces error), so it may not help to mention this special case in the "User Guide"?

**Comment by tomxp411** [comment]
Again, I think there’s a case for TO, THEN, and STEP to have their own entries, so someone unfamiliar with BASIC can look up the keywords. Those entries can be just a stub, pointing to IF, FOR, and GOTO, though.

and yes, the GO TO syntax should be mentioned, since it can come up. Some BASIC variants do actually write it that way, and while I could be wrong, I think the original Dartmouth BASIC wrote it as two words.

**Comment by memark2021** [comment]
Closing as per other discussion to reveiw if needing collapsing of TO, THEN, etc
