### ISSUE TITLE
APPENDIX : Statements - ON  (suggestion to adjust example code as it's not clear if it's meant to be as is?)

### ISSUE THREAD

**Issue by memark2021** [X16Community/x16-user-guide#17]
_Currently, code example is outputting "YUP! NOPE!" in succession (not sure if intended) -_
10 INPUT X
20 ON X GOTO 10,50,50,50
30 PRINT "NOPE!"
40 GOTO 10
50 PRINT "YUP!"
60 ON X GOTO 10,30,30
-----------------------------
I think it could be more complex (non-logical) as we pose it as a challenge to work out, with the highlighted box [**\NOTE**] -
10 INPUT X
20 ON X GOTO 10,30,50,80
30 PRINT "NOPE!"
40 GOTO 10
50 ON X GOTO 80,10,30,70
60 PRINT "YUP!"
70  END
80 ON X GOTO 30,10,50,60

If this is agreed, I can update the basic_command.tex file.

**Comment by jestin** [comment]
I got this example right from the VIC-20 manual.  I thought it was clever, but not too confusing, so I kept it.  I've used several examples from the original VIC-20 manual, sometimes with some modifications..
![image](https://github.com/X16Community/x16-user-guide/assets/669174/83b4ac10-f479-4802-8c3a-a813dde4d3db)

**Comment by memark2021** [comment]
That sounds like a 'no', keep as is.  No problem.
