### ISSUE TITLE
APPENDIX : Functions - RND    (description of operation in Appendix)

### ISSUE THREAD

**Issue by memark2021** [X16Community/x16-user-guide#19]
I am working on the RND function section in basic_commands.tex.

It's an interesting experience (reliving the past and working out how this function actually works)... I hope it's the same on the X16, so I expect some debate about my wording.  I ask that you be gentle 😅 with my first actual write up.  

It does make me wonder if we have access to all the BASIC V2 "descriptions" to be able to modify and rework for all items needed? Not sure what the process is so far with other existing keywords?   I guess I mean specific to X16 modifications if any?

I will try pull-request shortly on the changes after posting this.

**Comment by jestin** [comment]
This was merged in 39206a76c092aefca4a6cb4492918c2300c6bbb1
