### ISSUE TITLE
New BASIC keywords 2023-05-11

### ISSUE THREAD

**Issue by mooinglemur** [X16Community/x16-user-guide#7]
https://github.com/X16Community/x16-docs/pull/36/files

**Comment by mooinglemur** [comment]
Also https://github.com/X16Community/x16-docs/pull/37/files

**Comment by mooinglemur** [comment]
And https://github.com/X16Community/x16-docs/pull/38/files

**Comment by jestin** [comment]
Thanks!  I've either written the docs into the user guide or stubbed them in with the rest of the unfinished keywords so they won't be forgotten.
