### ISSUE TITLE
laundry issue

### ISSUE THREAD

**Issue by irmen** [X16Community/x16-user-guide#8]
A small typo is in getting_to_know_commanderx16.tex and readme.md and the image on the project's page;  it spells "SHIRT"  instead of "SHIFT"

**Comment by jestin** [comment]
Fixed in dc913a8

**Comment by jestin** [comment]
Fixed in dc913a8

**Comment by irmen** [comment]
the image for the "Clearing The Screen" tip still contains the typo, I guess you'll have to regenerate the pdf to fix that?

**Comment by jestin** [comment]
Thanks, I retook the screen shot and fixed it in the README example.  Didn't think I had it anywhere else, but I suppose that's the tip I used for the README example.  Nice catch!
